#+TITLE: smart-scholar.el
Smart Scholar for Emacs

* Introduction
** Installation
I haven't have chance to look into Melpa, so currently you are going
to install from GitHub. You can do this easily with
[[https://github.com/raxod502/straight.el][striaght.el]]. Basically,
you will need to do:

#+BEGIN_SRC elisp
(use-package smart-scholar
  :straight (smart-scholar :type git :host github
                           :repo "lihebi/smart-scholar.el"))
#+END_SRC

** Related work
- https://github.com/cute-jumper/gscholar-bibtex: Retrieve BibTeX
  entries from Google Scholar, ACM Digital Library, IEEE Xplore and
  DBLP. Might be useful for this project.
- https://www.zotero.org/: something like Mendeley. Open-source, in
  JS. Managed by some organization.
- Mendeley
- https://github.com/forrestbao/autoscholar: personal summarization


* Feature
** support major CS conferences

AI conferences
- [ ] NIPS
- [ ] ICML
- [ ] ICLR

Image Processing
- [ ] CVPR
- [ ] ICCV
- [ ] ECCV

NLP:
- [ ] ACL
- [ ] NAACL
- [ ] EMNLP

Programming Language:
- [ ] PLDI
- [ ] POPL

System:
- [ ] SOSP
- [ ] OSDI

For each of them, the package will manage
- crawl the website for a bib file list, for each year
- for each bib entry, figure out what is the pdf link
- download pdfs automatically, in background
- do all these at once

Also, I noticed that downloading htmls and pdfs from publishers
website is likely to be very slow, due to the visit limit of the
publishers. Thus, I might want to store a git mirror of all webpages
of these conferences. There might be copyright issues, but I think for
webpages that is fine.

The pdf cannot be mirrored: they are too large and has copyright
concern.

